### ISSUE TITLE
NullPointerException in AbstractAppender

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/atomix#186]
Observed this when running a cluster on gcloud. Cluster was running for a few days.

```
I 2020-03-16T21:43:19.393024133Z 2020-03-16 21:43:19.392 [] [raft-server-2-raft-partition-partition-1] ERROR io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - An uncaught exception occurred
 
I 2020-03-16T21:43:19.393050975Z java.lang.NullPointerException: null
	at io.atomix.protocols.raft.roles.AbstractAppender.builderWithPreviousEntry(AbstractAppender.java:114) ~[atomix-raft-3.2.0-20200316.115448-137.jar:?]
	at io.atomix.protocols.raft.roles.AbstractAppender.buildAppendEmptyRequest(AbstractAppender.java:100) ~[atomix-raft-3.2.0-20200316.115448-137.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:337) ~[atomix-raft-3.2.0-20200316.115448-137.jar:?]
	at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:130) ~[atomix-raft-3.2.0-20200316.115448-137.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.appendMembers(LeaderRole.java:1005) ~[atomix-raft-3.2.0-20200316.115448-137.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) [atomix-utils-3.2.0-20200316.115340-137.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by ChrisKujawa** [comment]
Have this as well on my benchmark:

```
java.lang.NullPointerException: null at io.atomix.protocols.raft.roles.AbstractAppender.builderWithPreviousEntry(AbstractAppender.java:114) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.protocols.raft.roles.AbstractAppender.buildAppendEmptyRequest(AbstractAppender.java:100) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.protocols.raft.roles.AbstractAppender.buildAppendRequest(AbstractAppender.java:79) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:369) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.protocols.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:130) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.protocols.raft.roles.LeaderRole.appendMembers(LeaderRole.java:1005) ~[atomix-raft-3.2.0-20200318.171657-141.jar:?] at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) [atomix-utils-3.2.0-20200318.171617-141.jar:?] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?] at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?] at java.lang.Thread.run(Unknown Source) [?:?]
```

https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&project=zeebe-io&authuser=1&minLogLevel=0&expandAll=false&timestamp=2020-03-19T13:50:39.206000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-min-based-offset%22%0Aresource.labels.pod_name%3D%22zell-min-based-offset-zeebe-1%22&scrollTimestamp=2020-03-19T14:04:09.979143980Z&dateRangeStart=2020-03-19T12:50:39.206Z&dateRangeEnd=2020-03-19T14:50:39.206Z&pinnedLogId=pvobmavtxcdp2cri2&pinnedLogTimestamp=2020-03-19T13:48:45.404837259Z

**Comment by deepthidevaki** [comment]
I had a very short look on this yesterday. There was another exception that caused the failure listener to close Raft. That leads to this exception later because the journal is closed. I will investigate this in detail.

**Comment by ChrisKujawa** [comment]
Would be nice because it seems for me like a blocker for us

**Comment by ChrisKujawa** [comment]
I think we have concurrent access of the reader. 

I think we are at some point in reseting the current reader,
https://github.com/zeebe-io/atomix/blob/develop/storage/src/main/java/io/atomix/storage/journal/FileChannelJournalSegmentReader.java#L103

which does:

```
      currentEntry = new Indexed<>(position.index() - 1, null, 0);
```

This means the entry is null. This is also what fails in the AbstractAppender then.

Not the indexed entry is null but the entry of this indexed entry. 
https://github.com/zeebe-io/atomix/blob/develop/protocols/raft/src/main/java/io/atomix/protocols/raft/roles/AbstractAppender.java#L114

And this only happens on reset

and this seems only to happen after compacting is done

**Comment by ChrisKujawa** [comment]
I think the problem here is that on compaction we remove all segments, writers and readers. They are hold in threadsafe datastructures, **BUT** after that we reset all remaining readers. The readers itself are **NOT** thread safe, which means we reset a reader which is currently used by another thread.

It is interesting that we never had problems before with that. Or do I miss interpret something.


https://github.com/zeebe-io/atomix/blob/develop/storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java#L574-L580
```java
  void resetHead(long index) {
    for (SegmentedJournalReader reader : readers) {
      if (reader.getNextIndex() < index) {
        reader.reset(index);
      }
    }
  }
```

This method is called by compact. Compact is called by our ZeebeStateMachine on a totally different context.

https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/clustering/atomix/ZeebeRaftStateMachine.java#L110-L123
```java
  private void safeCompact(final long index, final CompletableFuture<Void> future) {
    compactionContext.checkThread();
    logger.debug("Compacting up to index {}", index);

    try {
      final var startTime = System.currentTimeMillis();
      raft.getLog().compact(index);
      metrics.compactionTime(System.currentTimeMillis() - startTime);
      future.complete(null);
    } catch (final Exception e) {
      logger.error("Failed to compact up to index {}", index, e);
      future.completeExceptionally(e);
    }
  }
```




We use for each Member an own reader https://github.com/zeebe-io/atomix/blob/develop/protocols/raft/src/main/java/io/atomix/protocols/raft/cluster/impl/RaftMemberContext.java#L79 
When a reader is opened it is added to the collection and just returned to the caller.
https://github.com/zeebe-io/atomix/blob/develop/storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java
```java
  public SegmentedJournalReader<E> openReader(long index, SegmentedJournalReader.Mode mode) {
    SegmentedJournalReader<E> reader = new SegmentedJournalReader<>(this, index, mode);
    readers.add(reader);
    return reader;
  }
```

The receiver of this reader can change the internal state of the reader, when he resets, read's next etc. But also it seems the Journal itself can change the state, which is then not synchronized with the owner of the reader.

Ok probably the easiest way to fix it is to run in the same thread again as it is done in the default RaftServiceManager.

**Comment by npepinpe** [comment]
I think it was not a problem so much before with multiple snapshots, since probably most readers were ahead of the compaction. Implementing my RocksDB journal I came across this exact problem - marking open readers as stale across multiple threads, so I assume we should probably do the same here. I imagine before in Atomix, everything was done on the Raft context so it was not an issue, and it was our/my fault for assuming it was threadsafe :(

**Comment by ChrisKujawa** [comment]
I will try to run a benchmark with the same context lets see. Hey no worries its not your fault the implementation is total in-transparent and not easy to read/understand completely.

**Comment by npepinpe** [comment]
I'm not sure it will solve the problem entirely - by using the `JournalReader` in our own `LogStorageReader`, we are accessing these readers in different thread contexts, which is novel as far as Atomix is concerned.

**Comment by ChrisKujawa** [comment]
Have a benchmark running and it lookd really good

**Comment by ChrisKujawa** [comment]
But yes it is also really problematic when we still use it via the other readers

**Comment by npepinpe** [comment]
What's your feeling on this? We could temporarily merge this fix and then work on making the readers thread safe, as at least using the same context for compaction reduces the likelihood of this happening.

**Comment by ChrisKujawa** [comment]
yes had the same thinking I would like to do this. I can create a PR later; need to bring the kids to bed :sweat_smile:
