### ISSUE TITLE
Memory leak due to references in DefaultClusterCommunicationService

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/atomix#72]
**Expected behavior**

RaftSession objects are garbage collected after they are closed.

**Actual behavior**

After running Zeebe cluster for a few hours, we observed that some nodes went out of memory. From the heap dump, we could see that there are several  objects of `OperationResult`. The reason is that RaftSession objects which reference these, have references from `DefaultClusterCommunicationService`. When a raft session is closed,it unsubscribes from a subject. But this does not delete the reference to the handler. And this causes the memory leak.

![memory-leak](https://user-images.githubusercontent.com/1997478/69256640-16a5ab00-0bba-11ea-9b32-5f9364365566.png)

**Comment by npepinpe** [comment]
Just a note, we will soon not be using RaftSession or OperationResult anymore once we merge all my changes, I think.

**Comment by deepthidevaki** [comment]
:+1: This is a bug in `DefaultClusterCommunicationService`.

**Comment by ChrisKujawa** [comment]
It could be that this still is an issue. I have currently some OOM issues which shows the same (OperationResult etc), but I will recreate the cluster not 100% sure if the changes was really applied at the benchmark

**Comment by ChrisKujawa** [comment]
Seems to be the same issue 

![mem-leak](https://user-images.githubusercontent.com/2758593/69434620-47aee880-0d3e-11ea-9ad6-87e8ab868e4d.png)

![oom](https://user-images.githubusercontent.com/2758593/69434635-4ed5f680-0d3e-11ea-9334-7f40fd5eaa3e.png)

**Comment by deepthidevaki** [comment]
Before it was due to `DefaultClusterCommunicationService#unicastConsumers`. Now it is not removed from `NettyUnicastService#listeners`.

**Comment by ChrisKujawa** [comment]
Yes looks like that. :sweat_smile:

**Comment by ChrisKujawa** [comment]
Ok I think I know what is happening.

We observed lately that the primitive is recreated every time a snapshot was taken, because the snapshot is installed directly afterwards. This happens every 15 s. 
On recreation old sessions are removed from the session registry, see [here](https://github.com/zeebe-io/atomix/blob/develop/protocols/raft/src/main/java/io/atomix/protocols/raft/impl/RaftServiceManager.java#L320). But theses sessions are never closed. They are just garbage collected, but on open they register an listener for the reset request. This means we leak the reset request listeners, they are never removed.

![reset-listeners](https://user-images.githubusercontent.com/2758593/69437041-cf96f180-0d42-11ea-985b-c7ae9b16cdd0.png)


In the screenshot you can see the key, which says `raft-atomix-partition-1-reset-3`. Almost all keys are like this and this key is used by the reset listeners.

**Comment by deepthidevaki** [comment]
Good catch. I saw somewhere it closes all timed out sessions. But probably it is not closing all of them.
